-- MySQL Script generated by MySQL Workbench
-- Sat Feb 10 13:38:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Challenge
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Challenge
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Challenge` DEFAULT CHARACTER SET latin1 ;
USE `Challenge` ;

-- -----------------------------------------------------
-- Table `Challenge`.`campaignchannels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Challenge`.`campaignchannels` (
  `campaignid` INT(11) NOT NULL,
  `channelid` INT(11) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`campaignid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Challenge`.`campaigns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Challenge`.`campaigns` (
  `campaignid` INT(11) NOT NULL,
  `start` DATETIME NULL DEFAULT NULL,
  `end` DATETIME NULL DEFAULT NULL,
  `media` VARCHAR(45) NULL DEFAULT NULL,
  `productid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`campaignid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Challenge`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Challenge`.`customer` (
  `customerid` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `zip` VARCHAR(45) NULL DEFAULT NULL,
  `shipto` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `firstshipment` DATETIME NULL DEFAULT NULL,
  `lastshipment` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`customerid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Challenge`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Challenge`.`inventory` (
  `itemid` INT(11) NOT NULL,
  `productid` VARCHAR(45) NULL DEFAULT NULL,
  `brandid` VARCHAR(45) NULL DEFAULT NULL,
  `onhand` INT(11) NULL DEFAULT NULL,
  `warehouseid` INT(11) NULL DEFAULT NULL,
  `supplierid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`itemid`),
  UNIQUE INDEX `productid_UNIQUE` (`productid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Challenge`.`ordereditems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Challenge`.`ordereditems` (
  `orderid` INT(11) NOT NULL,
  `itemid` INT(11) NOT NULL,
  `productid` INT(11) NULL DEFAULT NULL,
  `quantity` INT(11) NULL DEFAULT NULL,
  `price` DECIMAL(10,0) NULL DEFAULT NULL,
  `unit` VARCHAR(45) NULL DEFAULT NULL,
  `weight` DECIMAL(10,0) NULL DEFAULT NULL,
  `note` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`orderid`, `itemid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Challenge`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Challenge`.`orders` (
  `orderid` INT(11) NOT NULL,
  `shipped` DATETIME NULL DEFAULT NULL,
  `cancelled` DATETIME NULL DEFAULT NULL,
  `scheduled` DATETIME NULL DEFAULT NULL,
  `returned` DATETIME NULL DEFAULT NULL,
  `orderedby` VARCHAR(45) NULL DEFAULT NULL,
  `shippedby` VARCHAR(45) NULL DEFAULT NULL,
  `customerid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`orderid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Challenge`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Challenge`.`product` (
  `productid` INT(11) NOT NULL,
  `upc` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`productid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Challenge`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Challenge`.`supplier` (
  `supplierid` INT(11) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `loaction` VARCHAR(45) NULL DEFAULT NULL,
  `zip` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`supplierid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Challenge`.`warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Challenge`.`warehouse` (
  `warehouseid` INT(11) NOT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `zip` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`warehouseid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
